{
  "x-generator": "NSwag v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "NcpAdminBlazor.Web",
    "version": "1.0.0"
  },
  "paths": {
    "/api/user": {
      "post": {
        "tags": [
          "User",
          "Api"
        ],
        "summary": "创建用户",
        "description": "创建一个新的后台用户",
        "operationId": "NcpAdminBlazorWebEndpointsUsersCreateUserEndpoint",
        "requestBody": {
          "x-name": "CreateUserRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NcpAdminBlazorWebEndpointsUsersCreateUserRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseDataOfCreateUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "security": [
          {
            "JWTBearerAuth": []
          }
        ]
      }
    },
    "/api/user/{userId}/delete": {
      "delete": {
        "tags": [
          "User",
          "Api"
        ],
        "summary": "删除用户",
        "description": "",
        "operationId": "NcpAdminBlazorWebEndpointsUsersDeleteUserEndpoint",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseData"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "JWTBearerAuth": []
          }
        ]
      }
    },
    "/api/user/login": {
      "post": {
        "tags": [
          "User",
          "Api"
        ],
        "summary": "用户登录",
        "description": "Description text goes here...",
        "operationId": "NcpAdminBlazorWebEndpointsUsersLoginEndpoint",
        "requestBody": {
          "x-name": "LoginRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NcpAdminBlazorWebEndpointsUsersLoginRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseDataOfMyTokenResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/user/profile": {
      "get": {
        "tags": [
          "User",
          "Api"
        ],
        "summary": "获取当前用户信息",
        "description": "返回当前登录用户的详细资料",
        "operationId": "NcpAdminBlazorWebEndpointsUsersProfileEndpoint",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseDataOfUserInfoDto"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "security": [
          {
            "JWTBearerAuth": []
          }
        ]
      }
    },
    "/api/user/refresh-token": {
      "post": {
        "tags": [
          "User",
          "Api"
        ],
        "operationId": "NcpAdminBlazorWebEndpointsUsersRefreshEndpoint",
        "requestBody": {
          "x-name": "TokenRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FastEndpointsSecurityTokenRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseDataOfMyTokenResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/user/create": {
      "post": {
        "tags": [
          "User",
          "Api"
        ],
        "summary": "创建用户",
        "operationId": "NcpAdminBlazorWebEndpointsUsersRegisterUserEndpoint",
        "requestBody": {
          "x-name": "RegisterUserRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NcpAdminBlazorWebEndpointsUsersRegisterUserRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseDataOfRegisterUserResponse"
                },
                "example": {
                  "data": {
                    "userId": "123"
                  },
                  "success": true,
                  "message": "",
                  "code": 0,
                  "errorData": []
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{userId}/update": {
      "post": {
        "tags": [
          "User",
          "Api"
        ],
        "summary": "更新用户信息",
        "description": "更新指定用户的基础信息",
        "operationId": "NcpAdminBlazorWebEndpointsUsersUpdateUserEndpoint",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "123"
          }
        ],
        "requestBody": {
          "x-name": "UpdateUserRequest",
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NcpAdminBlazorWebEndpointsUsersUpdateUserRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseData"
                },
                "example": {
                  "data": true,
                  "success": true,
                  "message": "",
                  "code": 0,
                  "errorData": []
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "security": [
          {
            "JWTBearerAuth": []
          }
        ]
      }
    },
    "/api/user/{userId}/profile": {
      "get": {
        "tags": [
          "User",
          "Api"
        ],
        "summary": "获取指定用户信息",
        "description": "根据用户ID获取详细资料，包括角色与权限",
        "operationId": "NcpAdminBlazorWebEndpointsUsersUserInfoEndpoint",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseDataOfUserInfoDto"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "security": [
          {
            "JWTBearerAuth": []
          }
        ]
      }
    },
    "/api/user/list": {
      "get": {
        "tags": [
          "User",
          "Api"
        ],
        "summary": "获取用户列表",
        "description": "按条件分页查询用户",
        "operationId": "NcpAdminBlazorWebEndpointsUsersUserListEndpoint",
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            }
          },
          {
            "name": "email",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            }
          },
          {
            "name": "phone",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            }
          },
          {
            "name": "realName",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            }
          },
          {
            "name": "pageIndex",
            "in": "query",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "countTotal",
            "in": "query",
            "required": true,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseDataOfPagedDataOfUserListItemDto"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "security": [
          {
            "JWTBearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "NetCorePalExtensionsDtoResponseDataOfCreateUserResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseData"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "data": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/NcpAdminBlazorWebEndpointsUsersCreateUserResponse"
                  }
                ]
              }
            }
          }
        ]
      },
      "NcpAdminBlazorWebEndpointsUsersCreateUserResponse": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "userId": {
            "type": "string"
          }
        }
      },
      "NetCorePalExtensionsDtoResponseData": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "errorData": {
            "type": "array",
            "items": {}
          }
        }
      },
      "NcpAdminBlazorWebEndpointsUsersCreateUserRequest": {
        "type": "object",
        "example": {
          "username": "admin",
          "password": "123456",
          "realName": "管理员",
          "email": "admin@example.com",
          "phone": "13800000000",
          "status": 1
        },
        "additionalProperties": false,
        "properties": {
          "username": {
            "type": "string",
            "example": "admin"
          },
          "password": {
            "type": "string",
            "example": "123456"
          },
          "realName": {
            "type": "string",
            "example": "管理员"
          },
          "email": {
            "type": "string",
            "example": "admin@example.com"
          },
          "phone": {
            "type": "string",
            "example": "13800000000"
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "example": 1
          }
        }
      },
      "NcpAdminBlazorWebEndpointsUsersDeleteUserRequest": {
        "type": "object",
        "additionalProperties": false
      },
      "NetCorePalExtensionsDtoResponseDataOfMyTokenResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseData"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "data": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/NcpAdminBlazorWebAspNetCoreMyTokenResponse"
                  }
                ]
              }
            }
          }
        ]
      },
      "NcpAdminBlazorWebAspNetCoreMyTokenResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/FastEndpointsSecurityTokenResponse"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "accessTokenExpiry": {
                "type": "string",
                "format": "date-time"
              },
              "refreshTokenExpiry": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        ]
      },
      "FastEndpointsSecurityTokenResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/FastEndpointsSecurityTokenRequest"
          },
          {
            "type": "object",
            "description": "base dto for access/refresh token responses",
            "additionalProperties": false,
            "properties": {
              "accessToken": {
                "type": "string",
                "description": "the jwt access token which will be valid for the duration specified by AccessExpiry"
              }
            }
          }
        ]
      },
      "FastEndpointsSecurityTokenRequest": {
        "type": "object",
        "description": "base dto for access/refresh token renewal requests",
        "additionalProperties": false,
        "properties": {
          "userId": {
            "type": "string",
            "description": "unique identifier of a user"
          },
          "refreshToken": {
            "type": "string",
            "description": "a single-use refresh token which will be valid for the duration specified by RefreshExpiry"
          }
        }
      },
      "NcpAdminBlazorWebEndpointsUsersLoginRequest": {
        "type": "object",
        "description": "登录请求体",
        "additionalProperties": false,
        "properties": {
          "username": {
            "type": "string",
            "description": "登录账号"
          },
          "password": {
            "type": "string",
            "description": "登录密码"
          }
        }
      },
      "NetCorePalExtensionsDtoResponseDataOfUserInfoDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseData"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "data": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/NcpAdminBlazorWebApplicationQueriesUserInfoDto"
                  }
                ]
              }
            }
          }
        ]
      },
      "NcpAdminBlazorWebApplicationQueriesUserInfoDto": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "realName": {
            "type": "string"
          },
          "status": {
            "type": "integer",
            "format": "int32"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "roles": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/NcpAdminBlazorWebApplicationQueriesUserRoleDto"
            }
          },
          "permissions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "NcpAdminBlazorWebApplicationQueriesUserRoleDto": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "roleName": {
            "type": "string"
          },
          "roleId": {
            "type": "string"
          }
        }
      },
      "NetCorePalExtensionsDtoResponseDataOfRegisterUserResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseData"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "data": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/NcpAdminBlazorWebEndpointsUsersRegisterUserResponse"
                  }
                ]
              }
            }
          }
        ]
      },
      "NcpAdminBlazorWebEndpointsUsersRegisterUserResponse": {
        "type": "object",
        "description": "创建用户的响应数据",
        "additionalProperties": false,
        "properties": {
          "userId": {
            "type": "string",
            "description": "用户ID"
          }
        }
      },
      "NcpAdminBlazorWebEndpointsUsersRegisterUserRequest": {
        "type": "object",
        "description": "创建用户请求Payload",
        "example": {
          "username": "admin",
          "password": "123"
        },
        "additionalProperties": false,
        "properties": {
          "username": {
            "type": "string",
            "description": "用户名",
            "example": "admin"
          },
          "password": {
            "type": "string",
            "description": "密码",
            "example": "123"
          }
        }
      },
      "NcpAdminBlazorWebEndpointsUsersUpdateUserRequest": {
        "type": "object",
        "example": {
          "username": "admin",
          "realName": "管理员",
          "email": "admin@example.com",
          "phone": "13800000000",
          "status": 1
        },
        "additionalProperties": false,
        "properties": {
          "username": {
            "type": "string",
            "example": "admin"
          },
          "realName": {
            "type": "string",
            "example": "管理员"
          },
          "email": {
            "type": "string",
            "example": "admin@example.com"
          },
          "phone": {
            "type": "string",
            "example": "13800000000"
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "example": 1
          }
        }
      },
      "NcpAdminBlazorWebEndpointsUsersUserInfoRequest": {
        "type": "object",
        "additionalProperties": false
      },
      "NetCorePalExtensionsDtoResponseDataOfPagedDataOfUserListItemDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/NetCorePalExtensionsDtoResponseData"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "data": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/NetCorePalExtensionsDtoPagedDataOfUserListItemDto"
                  }
                ]
              }
            }
          }
        ]
      },
      "NetCorePalExtensionsDtoPagedDataOfUserListItemDto": {
        "type": "object",
        "description": "分页数据模型",
        "additionalProperties": false,
        "properties": {
          "items": {
            "type": "array",
            "description": "分页数据",
            "items": {
              "$ref": "#/components/schemas/NcpAdminBlazorWebApplicationQueriesUserListItemDto"
            }
          },
          "total": {
            "type": "integer",
            "description": "数据总数",
            "format": "int32"
          },
          "pageIndex": {
            "type": "integer",
            "description": "当前页码，从1开始",
            "format": "int32"
          },
          "pageSize": {
            "type": "integer",
            "description": "每页数据条数",
            "format": "int32"
          }
        }
      },
      "NcpAdminBlazorWebApplicationQueriesUserListItemDto": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "realName": {
            "type": "string"
          },
          "status": {
            "type": "integer",
            "format": "int32"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "roleNames": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "NcpAdminBlazorWebEndpointsUsersGetUserListRequest": {
        "type": "object",
        "additionalProperties": false
      }
    },
    "securitySchemes": {
      "JWTBearerAuth": {
        "type": "http",
        "description": "Enter a JWT token to authorize the requests...",
        "scheme": "Bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}